sentry sourcemap 테스트

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -19,39 +19,9 @@ RUN \
 # Rebuild the source code only when needed
 FROM base AS builder
 
-ARG NEXT_PUBLIC_API_BASE_URL
-ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
-
-ARG NEXT_PUBLIC_SERVER_URL
-ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
-
-ARG NEXT_PUBLIC_FRONT_URL
-ENV NEXT_PUBLIC_FRONT_URL=${NEXT_PUBLIC_FRONT_URL}
-
-ARG NEXT_PUBLIC_SESSION_PW
-ENV NEXT_PUBLIC_SESSION_PW=${NEXT_PUBLIC_SESSION_PW}
-
-ARG NEXT_PUBLIC_ADMIN_ID1
-ENV NEXT_PUBLIC_ADMIN_ID1=${NEXT_PUBLIC_ADMIN_ID1}
-
-ARG NEXT_PUBLIC_ADMIN_ID2
-ENV NEXT_PUBLIC_ADMIN_ID2=${NEXT_PUBLIC_ADMIN_ID2}
-
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-
-# Next.js collects completely anonymous telemetry data about general usage.
-# Learn more here: https://nextjs.org/telemetry
-# Uncomment the following line in case you want to disable telemetry during the build.
-# ENV NEXT_TELEMETRY_DISABLED 1
-
-RUN \
-    if [ -f yarn.lock ]; then yarn run build; \
-    elif [ -f package-lock.json ]; then npm run build; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
 
 ARG NEXT_PUBLIC_API_BASE_URL
 ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
@@ -74,6 +44,21 @@ ENV NEXT_PUBLIC_ADMIN_ID2=${NEXT_PUBLIC_ADMIN_ID2}
 ARG RELEASE
 ENV RELEASE=${RELEASE}
 
+ARG SENTRY_AUTH_TOKEN
+ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
+
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN \
+    if [ -f yarn.lock ]; then yarn run build; \
+    elif [ -f package-lock.json ]; then npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
